services:
  db:
    image: mysql:8.3
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    env_file:
      - ".env.docker"
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/apps
      - static_volume:/apps/static
      - media_volume:/apps/media
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=beanlibapi.config.settings.docker
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
      - media_volume:/media
    depends_on:
      - server
    networks:
      - mynetwork

volumes:
  mysql_data:
  static_volume:
  media_volume:

networks:
  mynetwork: