# Generated by Django 4.2.16 on 2024-10-30 17:56

import beanlibapi.apps.authx.model_managers
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authx', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', beanlibapi.apps.authx.model_managers.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
