# Generated by Django 4.2.16 on 2024-10-24 16:43

import beanlibapi.apps.core.model_mixins
import beanlibapi.apps.core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bean',
            fields=[
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('variety', models.CharField(max_length=255)),
                ('process', models.CharField(max_length=255)),
                ('producer', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BeanDetail',
            fields=[
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('bean_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bean')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('uid', models.CharField(default=beanlibapi.apps.core.models.generate_sid, editable=False, max_length=24, primary_key=True, serialize=False, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('bean', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.bean')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, beanlibapi.apps.core.model_mixins.AttachmentMixin),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('uid', models.CharField(default=beanlibapi.apps.core.models.generate_sid, editable=False, max_length=24, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
