# Generated by Django 4.2.16 on 2024-11-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='filename',
            new_name='name',
        ),
        migrations.AddField(
            model_name='attachment',
            name='format',
            field=models.CharField(default='png', max_length=255),
        ),
    ]
