# Generated by Django 4.2.16 on 2024-11-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_rename_filename_attachment_name_attachment_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='format',
            field=models.CharField(max_length=255),
        ),
    ]
