# Generated by Django 4.2.16 on 2024-11-27 06:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_alter_attachment_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='bean',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='image',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='owner',
        ),
    ]
