# Generated by Django 4.2.16 on 2024-11-28 01:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_remove_attachment_bean_remove_attachment_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
